version: "3.8"

services:
  zebrad:
    image: docker.io/zfnd/zebra:latest
    container_name: zpulse-zebrad
    restart: unless-stopped
    ports:
      - "8232:8232" # Zcash JSON-RPC
      - "8233:8233" # Zcash Mainnet P2P
    volumes:
      - ./zebrad.toml:/etc/zebrad.toml:ro
      - zebrad-data:/home/zebra/.cache/zebra
    command: ["zebrad", "start", "--config", "/etc/zebrad.toml"]

volumes:
  zebrad-data:
