version: "3.8"

services:
  zebrad:
    image: docker.io/zfnd/zebra:latest
    container_name: zpulse-zebrad
    restart: unless-stopped
    ports:
      - "8232:8232" # Zcash JSON-RPC
      - "8233:8233" # Zcash Mainnet P2P
    environment:
      - ZEBRA_RPC__LISTEN_ADDR=0.0.0.0:8232
      - ZEBRA_RPC__ENABLE_COOKIE_AUTH=false
      - ZEBRA_CONSENSUS__CHECKPOINT_SYNC=true
    volumes:
      - zebrad-data:/home/zebra/.cache/zebra
    command: ["zebrad", "start"]

volumes:
  zebrad-data:
